# Generated by Django 4.2.7 on 2024-01-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Characteristic',
            },
        ),
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Density', models.IntegerField(null=True)),
                ('Level', models.IntegerField()),
                ('Efect', models.IntegerField(null=True)),
                ('Image', models.CharField(max_length=200)),
                ('OverMax', models.IntegerField(null=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RuneApp.category')),
                ('Characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RuneApp.characteristic')),
            ],
            options={
                'db_table': 'Rune',
            },
        ),
    ]
